### ISSUE TITLE
panic: index out of bounds: the len is 1008 but the index is 1008

### ISSUE THREAD

**Issue by dishmaker** [NathanRoyer/strpool#1]
Thanks for the awesome crate!

I've added a lot of strings to the pool.
But the program panics in the unsafe section.
```
thread '<unnamed>' panicked at strpool-1.0.2/src/lib.rs:145:49:
index out of bounds: the len is 1008 but the index is 1008
```

https://github.com/NathanRoyer/strpool/blob/036911961eca02328b1b375c69ec3539b0455cbe/src/lib.rs#L137-L145

**Comment by NathanRoyer** [comment]
Thank you for the report! I'll take a look.

**Comment by NathanRoyer** [comment]
Should be fixed by [latest commit](https://github.com/NathanRoyer/strpool/commit/74fa2690ea389daf89311afb4bfb4c13888aca4f). I updated the crate to version 1.0.3 which has the fix.

Thanks again for the report, let me know if you have any other issue.

**Comment by dishmaker** [comment]
Thanks!
It works on my really large set of unique strings.

However I've found it a little slower than `lasso::ThreadedRodeo`

Maybe some `O(n^2)` algorithms are slow. But otherwise, it's excellent!
